vim.g.loaded = 1
vim.g.loaded_netrwPlugin = 1
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.neovide_floating_blur_amount_x = 6.0
vim.g.neovide_floating_blur_amount_y = 6.0
vim.g.neovide_floating_opacity = 0.6
vim.g.neovide_refresh_rate = 120
vim.o.clipboard = "unnamedplus"
vim.o.completeopt = "menu,menuone,noselect"
vim.o.concealcursor = "nc"
vim.o.conceallevel = 2
vim.o.confirm = true
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.foldcolumn = "auto"
vim.o.guifont = "Iosevka NF:h16"
vim.o.ignorecase = true
vim.o.linebreak = true
vim.o.nrformats = "alpha,bin,hex"
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 5
vim.o.shiftwidth = 4
vim.o.showbreak = "↳ "
vim.o.signcolumn = "yes:1"
vim.o.smartcase = true
vim.o.termguicolors = true
vim.o.title = true
vim.o.undofile = true
vim.o.viewoptions = "folds,cursor"
